@ECHO OFF
SET PASSNAME=
SET /P PASSNAME=<USENAME.TXT
:RETRYUSER
CLS
ECHO Please enter a username:
SET USNAME=
SET /P USNAME=
IF %USNAME%==%PASSNAME% GOTO PASSWORD
GOTO RETRYUSER
:PASSWORD
SET PASSCODE=
SET /P PASSCODE=<PASS.TXT
CLS
ECHO Please enter the password for the account:
SET PSCODE=
SET /P PSCODE=
IF %PSCODE%==%PASSCOE% GOTO HOME
GOTO PASSWORD
:HOME
REM <YOUR CODE HERE>